HWTask/HWTask/Models/UserViewModel.cs
using HWTask.CoreModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HWTask.Models
{
    public class UserViewModel
    {
        public List<User> Users { get; set; }
        
        public int UserId { get; set; }

        public int FriendIndex { get; set; }
    }
}

HWTask/HWTask/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HWTask.Contexts;
using HWTask.CoreModels;
using HWTask.Models;
using HWTask.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HWTask.Controllers
{
    [Authorize]
    public class ChatController : Controller
    {
        private EncryptionService encryptionService;
        private readonly HWTaskDbContext dbContext;
        public ChatController(HWTaskDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public IActionResult Index(int? id)
        {
            if (id is null)
                return NotFound();

            var users = dbContext.Users.ToList();
            var user = users.FirstOrDefault(user => user.Email == User.Identity.Name);
            var friend = users.FirstOrDefault(user => user.Id == id);

            if (user is null || friend is null)
                return NotFound();

            var userFriend = dbContext.UserFriends.FirstOrDefault(x =>
            (x.UserId == user.Id && x.FriendId == friend.Id)
            || (x.UserId == friend.Id && x.FriendId == user.Id));

            if (userFriend is null)
            {
                return RedirectToAction("Invite", "Invitation", new { id = id });
            }
            var chat = dbContext.Chats.FirstOrDefault(x =>
            x.FirstUserId == user.Id && x.SecondUserId == friend.Id);
            var friendChat = dbContext.Chats.FirstOrDefault(x =>
            x.FirstUserId == friend.Id && x.SecondUserId == user.Id);

            return View(new ChatViewModel
            {
                Id = chat.Id,
                FriendChatId = friendChat.Id,
                FriendId = friend.Id,
                Messages = GetMessages(chat.Id),
                NewMessage = new Message(),
                UserKey=user.Key
            });

        }

        [HttpPost]
        public IActionResult SendMessage(ChatViewModel model)
        {
            encryptionService = new EncryptionService();

            var users = dbContext.Users.ToList();

            var user = users.FirstOrDefault(user => user.Email == User.Identity.Name);
            var friend = users.FirstOrDefault(user => user.Id == model.FriendId);
            var chat = dbContext.Chats.FirstOrDefault(x => x.FirstUserId == user.Id && x.SecondUserId == model.FriendId);
            var fritendChat = dbContext.Chats.FirstOrDefault(x =>
            x.FirstUserId == model.FriendId && x.SecondUserId == user.Id);


            var friendMessage = new Message
            {
                ChatId = fritendChat.Id,
                Sender = user,
                Recipient = dbContext.Users.FirstOrDefault(x => x.Id == model.FriendId),
                Text = model.NewMessage.Text,
                DateUpdated = DateTime.Now,
                CopyId = 0
            };
            friendMessage.Text = encryptionService.VigenereCrypt(friendMessage.Text, user.Key, false);
            dbContext.Messages.Add(friendMessage);
            dbContext.SaveChanges();
            int copyId = dbContext.Messages.OrderBy(x => x.Id).Last().Id;
            var message = new Message
            {
                ChatId = chat.Id,
                Sender = user,
                Recipient = dbContext.Users.FirstOrDefault(x => x.Id == model.FriendId),
                Text = model.NewMessage.Text,
                DateUpdated = DateTime.Now,
                CopyId = copyId
            };
            message.Text = encryptionService.VigenereCrypt(message.Text, user.Key, false);
            dbContext.Messages.Add(message);
            dbContext.SaveChanges();
            return RedirectToAction("Index", new { id = friend.Id });
        }

        [HttpGet]
        public IActionResult DeleteChat(int? id)
        {
            var chat = dbContext.Chats.FirstOrDefault(x => x.SecondUserId == id);
            List<Message> messages = dbContext.Messages.Where(x => x.ChatId == chat.Id).ToList();

            foreach (Message message in messages)
            {
                dbContext.Messages.Remove(message);
            }
            dbContext.SaveChanges();
            return RedirectToAction("Index", new { id = id });
        }

        public List<Message> GetMessages(int chatId)
        {
            encryptionService = new EncryptionService();
            var encryptMessages = dbContext.Messages.Where(x => x.ChatId == chatId);
            List<Message> messages = new List<Message>();

            foreach (var item in encryptMessages)
            {
                var newMessage = item;
                newMessage.Text = encryptionService.VigenereCrypt(item.Text, item.Sender.Key, true);
                messages.Add(newMessage);
            }
            return messages;
        }
    }
}

HWTask/HWTask/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HWTask.Contexts;
using HWTask.CoreModels;
using HWTask.Models;
using Microsoft.AspNetCore.Mvc;

namespace HWTask.Controllers
{
    public class UserController : Controller
    {
        private readonly HWTaskDbContext dbContext;
        public UserController(HWTaskDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public IActionResult Index()
        {
            return View(new UserViewModel
            {
                Users = dbContext.Users.Where(x => x.Visible == true).ToList(),
            });
        }

        
        public IActionResult Find(int? friendIndex)
        {
            List<User> users = new List<User>();
            User user = dbContext.Users.FirstOrDefault(x => x.Index == friendIndex);
            UserViewModel model = new UserViewModel();
            //model.UserId = user.Id;
            if (!(user is null))
            {
                users.Add(user);
                model.Users = users;
            }

            return View("Index", model);
        }

    }
}

HWTask/HWTask/Views/User/Index.cshtml
@model HWTask.Models.UserViewModel

<h1>Users</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                UserName
            </th>
            <th>
                Email
            </th>
            <th>

            </th>
        </tr>
    </thead>
    @if(!(Model.Users is null))
    { 
        @foreach (var item in Model.Users)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                @if (User.Identity.IsAuthenticated)
                {
                    if (User.Identity.Name == item.Email)
                    {
                        <td>You</td>
                    }
                    else
                    {
                        <td>
                            <a asp-controller="Chat" asp-action="Index" asp-route-id="@item.Id">Friend request</a>
                        </td>
                    }
                }
            </tr>
        }
    }
</table>

<form asp-action="Find" asp-controller="User">
    <div class="validation" asp-validation-summary="ModelOnly"></div>
    <div>
        <div class="form-group">
            <label asp-for="FriendIndex">Введите имя пользователия</label>
            <input type="text" asp-for="FriendIndex" />
            <span asp-validation-for="FriendIndex" />
        </div>
        <div class="form-group">
            <input type="submit" value="Change" class="btn btn-outline-dark" />
        </div>
    </div>
</form>