HWTask/HWTask/Models/ChatViewModel.cs
using HWTask.CoreModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HWTask.Models
{
    public class ChatViewModel
    {
        public int Id { get; set; }

        public int FriendChatId { get; set; }

        public int FriendId { get; set; }

        public IEnumerable<Message> Messages { get; set; }

        public Message NewMessage { get; set; }

        public string UserKey { get; set; }
    }
}

HWTask/HWTask/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HWTask.Contexts;
using HWTask.CoreModels;
using HWTask.Models;
using HWTask.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HWTask.Controllers
{
    [Authorize]
    public class ChatController : Controller
    {
        private EncryptionService encryptionService;
        private readonly HWTaskDbContext dbContext;
        public ChatController(HWTaskDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public IActionResult Index(int? id)
        {
            if (id is null)
                return NotFound();

            var users = dbContext.Users.ToList();
            var user = users.FirstOrDefault(user => user.Email == User.Identity.Name);
            var friend = users.FirstOrDefault(user => user.Id == id);

            if (user is null || friend is null)
                return NotFound();

            var userFriend = dbContext.UserFriends.FirstOrDefault(x =>
            (x.UserId == user.Id && x.FriendId == friend.Id)
            || (x.UserId == friend.Id && x.FriendId == user.Id));

            if (userFriend is null)
            {
                return RedirectToAction("Invite", "Invitation", new { id = id });
            }
            var chat = dbContext.Chats.FirstOrDefault(x =>
            x.FirstUserId == user.Id && x.SecondUserId == friend.Id);
            var friendChat = dbContext.Chats.FirstOrDefault(x =>
            x.FirstUserId == friend.Id && x.SecondUserId == user.Id);

            return View(new ChatViewModel
            {
                Id = chat.Id,
                FriendChatId = friendChat.Id,
                FriendId = friend.Id,
                Messages = GetMessages(chat.Id),
                NewMessage = new Message(),
                UserKey=user.Key
            });

        }

        [HttpPost]
        public IActionResult SendMessage(ChatViewModel model)
        {
            encryptionService = new EncryptionService();

            var users = dbContext.Users.ToList();

            var user = users.FirstOrDefault(user => user.Email == User.Identity.Name);
            var friend = users.FirstOrDefault(user => user.Id == model.FriendId);
            var chat = dbContext.Chats.FirstOrDefault(x => x.FirstUserId == user.Id && x.SecondUserId == model.FriendId);
            var fritendChat = dbContext.Chats.FirstOrDefault(x =>
            x.FirstUserId == model.FriendId && x.SecondUserId == user.Id);


            var friendMessage = new Message
            {
                ChatId = fritendChat.Id,
                Sender = user,
                Recipient = dbContext.Users.FirstOrDefault(x => x.Id == model.FriendId),
                Text = model.NewMessage.Text,
                DateUpdated = DateTime.Now,
                CopyId = 0
            };
            friendMessage.Text = encryptionService.VigenereCrypt(friendMessage.Text, user.Key, false);
            dbContext.Messages.Add(friendMessage);
            dbContext.SaveChanges();
            int copyId = dbContext.Messages.OrderBy(x => x.Id).Last().Id;
            var message = new Message
            {
                ChatId = chat.Id,
                Sender = user,
                Recipient = dbContext.Users.FirstOrDefault(x => x.Id == model.FriendId),
                Text = model.NewMessage.Text,
                DateUpdated = DateTime.Now,
                CopyId = copyId
            };
            message.Text = encryptionService.VigenereCrypt(message.Text, user.Key, false);
            dbContext.Messages.Add(message);
            dbContext.SaveChanges();
            return RedirectToAction("Index", new { id = friend.Id });
        }

        [HttpGet]
        public IActionResult DeleteChat(int? id)
        {
            var chat = dbContext.Chats.FirstOrDefault(x => x.SecondUserId == id);
            List<Message> messages = dbContext.Messages.Where(x => x.ChatId == chat.Id).ToList();

            foreach (Message message in messages)
            {
                dbContext.Messages.Remove(message);
            }
            dbContext.SaveChanges();
            return RedirectToAction("Index", new { id = id });
        }

        public List<Message> GetMessages(int chatId)
        {
            encryptionService = new EncryptionService();
            var encryptMessages = dbContext.Messages.Where(x => x.ChatId == chatId);
            List<Message> messages = new List<Message>();

            foreach (var item in encryptMessages)
            {
                var newMessage = item;
                newMessage.Text = encryptionService.VigenereCrypt(item.Text, item.Sender.Key, true);
                messages.Add(newMessage);
            }
            return messages;
        }
    }
}

HWTask/HWTask/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HWTask.Contexts;
using HWTask.Models;
using HWTask.Services;
using Microsoft.AspNetCore.Mvc;

namespace HWTask.Controllers
{
    public class MessageController : Controller
    {
        private readonly HWTaskDbContext dbContext;
        private EncryptionService encryptionService;

        public MessageController(HWTaskDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        /*public IActionResult Index()
        {
            return View();
        }*/

        [HttpGet]
        public IActionResult Delete(int? id, int? friendId)
        {
            dbContext.Messages.Remove(dbContext.Messages.FirstOrDefault(x => x.Id == id));
            dbContext.SaveChanges();
            return RedirectToAction("Index", "Chat", new { id = friendId });
        }

        [HttpGet]
        public IActionResult Edit(int id, int copyId, int messageId, string userKey, int friendId)
        {
            return View(new MessageEditViewModel
            {
                Id = id,
                CopyId = copyId,
                MessageId = messageId,
                UserKey=userKey,
                FriendId = friendId
            });
        }

        [HttpPost]
        public IActionResult Edit(MessageEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                encryptionService = new EncryptionService();

                var message = dbContext.Messages.FirstOrDefault(x => x.Id == model.MessageId);
                var copyMessage = dbContext.Messages.FirstOrDefault(x => x.Id == model.CopyId);

                message.Text = encryptionService.VigenereCrypt(model.Text, model.UserKey, false);
                copyMessage.Text = encryptionService.VigenereCrypt(model.Text, model.UserKey, false);

                dbContext.SaveChanges();

                return RedirectToAction("Index", "Chat", new { id = model.FriendId });
            }

            return View(model);
        }
    }
}

HWTask/HWTask/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HWTask.Contexts;
using HWTask.CoreModels;
using HWTask.Models;
using Microsoft.AspNetCore.Mvc;

namespace HWTask.Controllers
{
    public class UserController : Controller
    {
        private readonly HWTaskDbContext dbContext;
        public UserController(HWTaskDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public IActionResult Index()
        {
            return View(new UserViewModel
            {
                Users = dbContext.Users.Where(x => x.Visible == true).ToList(),
            });
        }

        
        public IActionResult Find(int? friendIndex)
        {
            List<User> users = new List<User>();
            User user = dbContext.Users.FirstOrDefault(x => x.Index == friendIndex);
            UserViewModel model = new UserViewModel();
            //model.UserId = user.Id;
            if (!(user is null))
            {
                users.Add(user);
                model.Users = users;
            }

            return View("Index", model);
        }

    }
}

HWTask/HWTask/Views/Chat/Index.cshtml
@model HWTask.Models.ChatViewModel
<h1>Чат</h1>
@if (Model.Messages.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    <p>Отправитель</p>
                </th>
                <th>
                    <p>Соообщение</p>
                </th>
                <th>
                    <p>Время</p>
                </th>
                <th>

                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Messages)
            {
                HWTask.CoreModels.User sender = new HWTask.CoreModels.User();
                HWTask.CoreModels.User recipient = new HWTask.CoreModels.User();

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Sender.UserName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Text)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateUpdated)
                    </td>
                    <td>
                        @if (Model.FriendId == item.Recipient.Id)
                        {
                            <a asp-controller="Message" asp-action="Edit" 
                               asp-route-Id="@Model.Id" 
                               asp-route-MessageId="@item.Id" 
                               asp-route-CopyId="@item.CopyId"
                               asp-route-UserKey="@Model.UserKey"
                               asp-route-FriendId="@Model.FriendId">Изменить</a>
                            <a asp-controller="Message" asp-action="Delete" asp-route-Id="@item.Id" asp-route-friendId="@item.Recipient.Id">Удалить</a>
                        }

                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h2>У Вас пока нет сообщений с этим пользователем.</h2>
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="SendMessage">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="FriendChatId" />
            <input type="hidden" asp-for="FriendId" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Новое сообщение</label>
                <input asp-for="NewMessage.Text" class="form-control" autocomplete="off"/>
                <span asp-validation-for="NewMessage.Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Отправить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="User" asp-action="Index">К списку пользователей</a>
</div>
<div>
    <a asp-controller="Chat" asp-action="DeleteChat" asp-route-id="@Model.FriendId">Удалить переписку для себя</a>
</div>