HWTask/HWTask/Controllers/FriendController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HWTask.Contexts;
using HWTask.CoreModels;
using HWTask.Models;
using Microsoft.AspNetCore.Mvc;

namespace HWTask.Controllers
{
    public class FriendController : Controller
    {
        private readonly HWTaskDbContext dbContext;
        public FriendController(HWTaskDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public IActionResult Index()
        {
            var user = dbContext.Users.FirstOrDefault(x => x.Email == User.Identity.Name);

            if (user is null)
                return NotFound();


            Dictionary<User, bool> confirmsFriends = new Dictionary<User, bool>();
            List<UserFriend> userFriends = dbContext.UserFriends.Where(x => (x.FriendId == user.Id) || (x.UserId == user.Id)).ToList();
            var users = dbContext.Users;
            List<bool> confirms = new List<bool>();
            List<User> friends = new List<User>();

            foreach (UserFriend userFriend in userFriends)
            {
                User friend = new User();
                if (userFriend.UserId == user.Id)
                    friend = users.FirstOrDefault(x => x.Id == userFriend.FriendId);
                else
                    friend = users.FirstOrDefault(x => x.Id == userFriend.UserId);

                if (!confirmsFriends.ContainsKey(friend))
                    confirmsFriends.Add(friend, userFriend.IsVerified);
            }

            return View(new FriendsViewModel
            {
                ConfirmsFriends = confirmsFriends
            });
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            dbContext.UserFriends.Remove(dbContext.UserFriends.FirstOrDefault(x => x.IsVerified && x.FriendId == id));
            dbContext.UserFriends.Remove(dbContext.UserFriends.FirstOrDefault(x => x.IsVerified && x.UserId == id));
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

HWTask/HWTask/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HWTask.Contexts;
using Microsoft.AspNetCore.Mvc;

namespace HWTask.Controllers
{
    public class ProfileController : Controller
    {
        private readonly HWTaskDbContext dbContext;

        public ProfileController(HWTaskDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public IActionResult Index()
        {
            var user = dbContext.Users.FirstOrDefault(x => x.Email == User.Identity.Name);
            return View(user.Index);
        }
    }
}

HWTask/HWTask/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HWTask.Contexts;
using HWTask.CoreModels;
using HWTask.Models;
using Microsoft.AspNetCore.Mvc;

namespace HWTask.Controllers
{
    public class UserController : Controller
    {
        private readonly HWTaskDbContext dbContext;
        public UserController(HWTaskDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public IActionResult Index()
        {
            return View(new UserViewModel
            {
                Users = dbContext.Users.Where(x => x.Visible == true).ToList(),
            });
        }

        
        public IActionResult Find(int? friendIndex)
        {
            List<User> users = new List<User>();
            User user = dbContext.Users.FirstOrDefault(x => x.Index == friendIndex);
            UserViewModel model = new UserViewModel();
            //model.UserId = user.Id;
            if (!(user is null))
            {
                users.Add(user);
                model.Users = users;
            }

            return View("Index", model);
        }

    }
}

HWTask/HWTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HWTask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HWTask</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Friend" asp-action="Index">Friends</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="Index">Profile</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - HWTask - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>